# Default configuration for cortexm-softmmu

CONFIG_CORTEXM=y
CONFIG_ARM_GIC=y
CONFIG_ARM_GIC_KVM=$(CONFIG_KVM)
CONFIG_ARM_TIMER=y
CONFIG_ARM_MPTIMER=y
CONFIG_STELLARIS=y
CONFIG_STELLARIS_INPUT=y
CONFIG_STELLARIS_ENET=y
CONFIG_PTIMER=y
CONFIG_PCI=y
CONFIG_STM32=y
CONFIG_KINETIS=n
CONFIG_LPC=n
CONFIG_TIVA=n
CONFIG_XMC=n
CONFIG_SAM=n
CONFIG_SOFTMMU=y